-- สร้าง privileges table
CREATE TABLE privileges (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  description TEXT,
  level INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- สร้าง users table
CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  name TEXT NOT NULL,
  privilege_id INTEGER NOT NULL REFERENCES privileges(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- สร้าง egg_session table
CREATE TABLE egg_session (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id),
  image_path TEXT NOT NULL,
  egg_count INTEGER NOT NULL,
  success_percent REAL NOT NULL,
  grade0_count INTEGER NOT NULL,
  grade1_count INTEGER NOT NULL,
  grade2_count INTEGER NOT NULL,
  grade3_count INTEGER NOT NULL,
  grade4_count INTEGER NOT NULL,
  grade5_count INTEGER NOT NULL,
  day TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- สร้าง egg_item table
CREATE TABLE egg_item (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id INTEGER NOT NULL REFERENCES egg_session(id),
  grade INTEGER NOT NULL,
  confidence REAL NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE privileges ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE egg_session ENABLE ROW LEVEL SECURITY;
ALTER TABLE egg_item ENABLE ROW LEVEL SECURITY;

-- Create RLS policies
-- Allow public read access to privileges
CREATE POLICY "Public read access to privileges" ON privileges
  FOR SELECT USING (true);

-- Allow users to read their own data
CREATE POLICY "Users can read own data" ON users
  FOR SELECT USING (auth.uid()::text = id::text);

-- Allow users to update their own data
CREATE POLICY "Users can update own data" ON users
  FOR UPDATE USING (auth.uid()::text = id::text);

-- Allow users to insert their own data
CREATE POLICY "Users can insert own data" ON users
  FOR INSERT WITH CHECK (auth.uid()::text = id::text);

-- Allow users to read own egg sessions
CREATE POLICY "Users can read own egg sessions" ON egg_session
  FOR SELECT USING (auth.uid()::text = user_id::text);

-- Allow users to insert own egg sessions
CREATE POLICY "Users can insert own egg sessions" ON egg_session
  FOR INSERT WITH CHECK (auth.uid()::text = user_id::text);

-- Allow users to read own egg items through sessions
CREATE POLICY "Users can read own egg items" ON egg_item
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM egg_session 
      WHERE egg_session.id = egg_item.session_id 
      AND egg_session.user_id = auth.uid()::text::bigint
    )
  );

-- Allow users to insert own egg items
CREATE POLICY "Users can insert own egg items" ON egg_item
  FOR INSERT WITH CHECK (
    EXISTS (
      SELECT 1 FROM egg_session 
      WHERE egg_session.id = egg_item.session_id 
      AND egg_session.user_id = auth.uid()::text::bigint
    )
  );

-- เพิ่มข้อมูลเริ่มต้น
INSERT INTO privileges (name, description, level) VALUES 
('Admin', 'System administrator', 1),
('Community internship supervisor', 'หัวหน้าสหกิจชุมชน', 2),
('Farmer', 'เกษตรกร', 3),
('General user ', 'ผู้ใช้ทั่วไป', 4);

-- Create function to handle user registration
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.users (email, name, privilege_id)
  VALUES (
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'name', 'New User'),
    2  -- Default to 'User' privilege
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Create trigger to handle new user registration
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
