-- Complete Supabase Database Setup for NumberEgg App
-- This script creates all tables, RLS policies, and initial data

-- Enable Row Level Security
ALTER DATABASE SET "row_level_security" = true;

-- Create privileges table
CREATE TABLE IF NOT EXISTS privileges (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  description TEXT,
  level INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create users table
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  name TEXT NOT NULL,
  privilege_id INTEGER NOT NULL REFERENCES privileges(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create egg_session table
CREATE TABLE IF NOT EXISTS egg_session (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id),
  image_path TEXT NOT NULL,
  egg_count INTEGER NOT NULL,
  success_percent REAL NOT NULL,
  big_count INTEGER NOT NULL,
  medium_count INTEGER NOT NULL,
  small_count INTEGER NOT NULL,
  day TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create egg_item table
CREATE TABLE IF NOT EXISTS egg_item (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id INTEGER NOT NULL REFERENCES egg_session(id),
  grade INTEGER NOT NULL,
  confidence REAL NOT NULL
);

-- Enable RLS on all tables
ALTER TABLE privileges ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE egg_session ENABLE ROW LEVEL SECURITY;
ALTER TABLE egg_item ENABLE ROW LEVEL SECURITY;

-- Create RLS Policies

-- Privileges table - everyone can read, only admins can write
CREATE POLICY "Anyone can view privileges" ON privileges
  FOR SELECT USING (true);

CREATE POLICY "Admins can insert privileges" ON privileges
  FOR INSERT WITH CHECK (
    EXISTS (
      SELECT 1 FROM users 
      WHERE users.id = auth.uid() 
      AND users.privilege_id = 1
    )
  );

-- Users table policies
CREATE POLICY "Users can view own profile" ON users
  FOR SELECT USING (auth.uid() = id);

CREATE POLICY "Users can update own profile" ON users
  FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Admins can view all users" ON users
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM users 
      WHERE users.id = auth.uid() 
      AND users.privilege_id = 1
    )
  );

-- Egg session policies
CREATE POLICY "Users can view own sessions" ON egg_session
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can create own sessions" ON egg_session
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own sessions" ON egg_session
  FOR UPDATE USING (auth.uid() = user_id);

-- Egg item policies
CREATE POLICY "Users can view own egg items" ON egg_item
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM egg_session 
      WHERE egg_session.id = session_id 
      AND egg_session.user_id = auth.uid()
    )
  );

CREATE POLICY "Users can create own egg items" ON egg_item
  FOR INSERT WITH CHECK (
    EXISTS (
      SELECT 1 FROM egg_session 
      WHERE egg_session.id = session_id 
      AND egg_session.user_id = auth.uid()
    )
  );

-- Insert initial data
INSERT INTO privileges (name, description, level) VALUES 
('Admin', 'System administrator', 1),
('หัวหน้าสหกิจชุมชน', 'Community internship supervisor', 2),
('เกษตรกร', 'Farmer', 3),
('ผู้ใช้ทั่วไป', 'General user', 4)
ON CONFLICT (name) DO NOTHING;

-- Create storage bucket for egg images
INSERT INTO storage.buckets (id, name, public) VALUES ('egg-images', 'egg-images', true)
ON CONFLICT (id) DO NOTHING;

-- Storage policies
CREATE POLICY "Anyone can view egg images" ON storage.objects
  FOR SELECT USING (bucket_id = 'egg-images');

CREATE POLICY "Users can upload own egg images" ON storage.objects
  FOR INSERT WITH CHECK (
    bucket_id = 'egg-images' 
    AND auth.role() = 'authenticated'
  );

CREATE POLICY "Users can update own egg images" ON storage.objects
  FOR UPDATE USING (
    bucket_id = 'egg-images' 
    AND auth.role() = 'authenticated'
  );

-- Create functions for authentication
CREATE OR REPLACE FUNCTION authenticate_user(email_param TEXT, password_param TEXT)
RETURNS TABLE(id BIGINT, email TEXT, name TEXT, privilege_id INTEGER)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT u.id, u.email, u.name, u.privilege_id
  FROM users u
  WHERE u.email = email_param AND u.password = password_param;
END;
$$;

-- Create function for user registration
CREATE OR REPLACE FUNCTION register_user(email_param TEXT, password_param TEXT, name_param TEXT)
RETURNS TABLE(id BIGINT, email TEXT, name TEXT, privilege_id INTEGER)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  INSERT INTO users (email, password, name, privilege_id)
  VALUES (email_param, password_param, name_param, 4)
  RETURNING id, email, name, privilege_id;
  
  RETURN QUERY
  SELECT u.id, u.email, u.name, u.privilege_id
  FROM users u
  WHERE u.email = email_param;
END;
$$;
